name: homelab

include:
  - ./services/cloudflare-tunnel/compose.yaml
  - ./services/cybarbot/compose.yaml
  - ./services/forgejo/compose.yaml
  - ./services/nextcloud/compose.yaml
  - ./services/searxng/compose.yaml
  - ./services/vaultwarden/compose.yaml
