networks:
  searxng:

volumes:
  searxng-cache:
  searxng-data:

services:
  searxng-cache:
    container_name: searxng-cache
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 300 5 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - searxng-cache:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 20M

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - 8888:8080
    depends_on:
      - searxng-cache
    volumes:
      - ./config:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    env_file: ".env"
    environment:
      SEARXNG_BASE_URL: http://${SEARXNG_HOSTNAME:-localhost}/
      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.json
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 160M
